<section
        class="w-full max-w-full h-[120dvh] lg:h-[100vh] min-h-[700px] flex flex-col lg:flex-row overflow-hidden relative">
        <!-- Text overlay for the map -->

        <!-- Left Map Area -->
        <div
            class="w-full h-[65vh] md:h-[80vh] lg:h-auto lg:flex-1 relative overflow-hidden flex items-start justify-center p-4 lg:p-0">
            <!-- Tích hợp hình ảnh bản đồ tĩnh -->
            <img src="<?php echo get_template_directory_uri(); ?>/assets/images/connect.png" alt="Bản đồ kết nối"
                class="w-full h-full object-contain hover:scale-[1.02] transition-transform duration-500"
                data-aos="zoom-in" data-aos-duration="1200" data-aos-delay="200" loading="lazy" title="Bản đồ kết nối">
        </div>

        <!-- Right Legend Sidebar -->
        <div
            class="w-full lg:w-[320px] xl:w-[450px] h-[55vh] lg:h-auto border-t border-white/10 lg:border-t-0 lg:border-l flex flex-col z-40 shadow-[-20px_0_50px_rgba(0,0,0,0.5)]">
            <div class="p-4 lg:p-6 lg:pb-4 border-b border-white/10 shrink-0">
                <h2
                    class="text-2xl font-bold playfair uppercase tracking-wider mb-4 bg-gradient-to-r from-[#f0e0ca] to-[#d4ae6f] bg-clip-text text-transparent">
                    Bản Đồ kết Nối</h2>

                <!-- Tabs Container -->
                <div class="relative w-full group py-1">
                    <button id="legend-prev"
                        class="absolute -left-2 top-1/2 -translate-y-1/2 z-20 w-8 h-8 rounded-full bg-[#0e1e2e]/95 text-[#d4ae6f] items-center justify-center backdrop-blur shadow-[0_0_10px_rgba(212,174,111,0.3)] border border-[#d4ae6f]/30 opacity-0 group-hover:opacity-100 transition-opacity disabled:opacity-0 hidden md:flex">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7">
                            </path>
                        </svg>
                    </button>

                    <div class="swiper legend-swiper px-1">
                        <div id="legend-tabs" class="swiper-wrapper items-center pb-2">
                            <!-- Generated by JS -->
                        </div>
                    </div>

                    <button id="legend-next"
                        class="absolute -right-2 top-1/2 -translate-y-1/2 z-20 w-8 h-8 rounded-full bg-[#0e1e2e]/95 text-[#d4ae6f] items-center justify-center backdrop-blur shadow-[0_0_10px_rgba(212,174,111,0.3)] border border-[#d4ae6f]/30 opacity-0 group-hover:opacity-100 transition-opacity disabled:opacity-0 hidden md:flex">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7">
                            </path>
                        </svg>
                    </button>
                </div>
            </div>

            <div id="legend-container" class="flex-1 overflow-y-auto p-6 pt-4 legend-scroll overflow-x-hidden relative">
                <!-- Generated by JS -->
            </div>
        </div>
    </section>
